name: Add URL
description: Use this form to add an individual URL to the newsfeed.
title: "[Add URL]: "
labels: ["add-url"]
projects: []
assignees: []
body:
  - type: input
    id: url
    attributes:
      label: URL
      description: The URL of the news article.
      placeholder: https://example.com/news/article
      value: ""
      required: true