# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:

  # Runs on pull requests targeting the default branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Prevent duplicate ID's in the data.json
        run: |
          node .github/workflows/duplicate-ids-detection.js

      - name: Build project
        env:
          NODE_ENV: ${{ vars.NODE_ENV }} # use the vars to indicate the env that is uesd in the react-config.js to set the base url / folder
          REACT_APP_BUILDNUMBER: ${{ github.run_number }}
        run: |
          export NODE_ENV=$NODE_ENV
          export REPO_NAME="$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)"
          echo "Building in repo [$REPO_NAME] with build number [$REACT_APP_BUILDNUMBER] for [$NODE_ENV] environment."
          npm run build

          # copy the index file from the dist folder into the 404 file
          cp dist/index.html dist/404.html

      - name: Listfiles
        run: |
          cd dist
          ls -la
